### ISSUE TITLE
multichannel recording

### ISSUE THREAD

**Issue by germanstudent** [Luzifer/livecast#1]
Just wanted to let you know, that I had very bad experiences with mumble multichannel recordings. (channels out of sync -> unnecessary post production effort) 

I think choosing `downmix` for the client or setting this as a config option would be best.

**Comment by Luzifer** [comment]
Using integrated recording isn't planned because this would require user interaction. I'm not yet sure whether I want to use the official client or search for alternatives.

The workflow is to use `Mumble-Server -> Mumble Client -> Darkice -> Icecast -> streamripper` as for example the recording for Bruellaffencouch is using it curently.
